### ISSUE TITLE
Failed to load the atom-watchless package

### ISSUE THREAD

**Issue by 9994444ggg** [Ryjek0/atom-watchless#1]
[[Enter](url) steps to reproduce:]

1. ...
2. ...

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: MEDION
**Thrown From**: [atom-watchless](https://github.com/Ryjek0/atom-watchless) package 0.7.0

### Stack Trace

Failed to load the atom-watchless package

```
At primordials is not defined

ReferenceError: primordials is not defined
    at internal/util/inspect.js:70:20
    at req_ (/packages/atom-watchless/node_modules/natives/index.js:143:24)
    at require (/packages/atom-watchless/node_modules/natives/index.js:116:12)
    at internal/url.js:3:21
    at req_ (/packages/atom-watchless/node_modules/natives/index.js:143:24)
    at require (/packages/atom-watchless/node_modules/natives/index.js:116:12)
    at fs.js:57:29
    at req_ (/packages/atom-watchless/node_modules/natives/index.js:143:24)
    at /packages/atom-watchless/node_modules/natives/index.js:55:10)
    at /packages/atom-watchless/node_modules/graceful-fs/fs.js:1:192)
    at /packages/atom-watchless/node_modules/graceful-fs/fs.js:3:3)
    at Module.get_Module._compile (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-watchless/node_modules/graceful-fs/graceful-fs.js:3:27)
    at /packages/atom-watchless/node_modules/graceful-fs/graceful-fs.js:160:3)
    at Module.get_Module._compile (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-watchless/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:3:10)
    at /packages/atom-watchless/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:18:3)
    at Module.get_Module._compile (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:147498)
```

### Commands

```
```

### Non-Core Packages

```
a-package-loader 1.0.0 
atom-folding 0.0.9 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-watch 0.1.0 
atom-watcher 1.1.7 
atom-watchless 0.7.0 
auto-detect-indentation 1.3.0 
auto-run 0.2.1 
autocomplete-clang 0.13.1 
autoreload-package-service 0.0.4 
build 0.70.0 
build-platformio 1.2.4 
busy-signal 2.0.1 
compile-watch 0.1.4 
event-watch 4.1.11 
f5-run-file 0.1.1 
fetch-from-url 0.1.2 
file-icons 2.1.47 
file-open-watch 1.0.0 
file-watcher 2.0.0 
hey-pane 1.2.0 
indent-detective 0.4.0 
intentions 2.1.1 
jsformat 0.9.3 
language-ini 1.25.0 
linter 3.4.0 
linter-gcc2 0.8.8 
linter-ui-default 3.4.1 
platformio-aia 0.0.5 
platformio-ide 2.7.2 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.1 
platomformio 0.7.1 
rdocumentation-browser 1.1.4 
reload-button 0.1.0 
reload-window 1.0.0 
reload-workspace-button 0.1.2 
remove-all-keybindings 0.2.1 
run 0.0.1 
run-in-atom 1.0.5 
show-in-folder 0.6.0 
teletype 0.13.4 
teletype-revit-linker 1.0.0 
terminal-commands 1.5.0 
tokamak-terminal 10.0.1 
tool-bar 1.4.4 
zentabs 0.8.9 
```

**Comment by 9994444ggg** [comment]
> [[Geben Sie](url) die zu reproduzierenden Schritte ein:]
> 
> 1. ...
> 2. ...
> 
> **Atom**: 1.50.0 x64 **Elektron**: 5.0.13 **OS:** MEDION **geworfen aus**: [Atom-watchless-Paket](https://github.com/Ryjek0/atom-watchless) 0.7.0
> 
> ### Stapelüberwachung
> Das atom-watchless-Paket konnte nicht geladen werden
> 
> ```
> At primordials is not defined
> 
> ReferenceError: primordials is not defined
>     at internal/util/inspect.js:70:20
>     at req_ (/packages/atom-watchless/node_modules/natives/index.js:143:24)
>     at require (/packages/atom-watchless/node_modules/natives/index.js:116:12)
>     at internal/url.js:3:21
>     at req_ (/packages/atom-watchless/node_modules/natives/index.js:143:24)
>     at require (/packages/atom-watchless/node_modules/natives/index.js:116:12)
>     at fs.js:57:29
>     at req_ (/packages/atom-watchless/node_modules/natives/index.js:143:24)
>     at /packages/atom-watchless/node_modules/natives/index.js:55:10)
>     at /packages/atom-watchless/node_modules/graceful-fs/fs.js:1:192)
>     at /packages/atom-watchless/node_modules/graceful-fs/fs.js:3:3)
>     at Module.get_Module._compile (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:147498)
>     at Object.value [as .js] (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:151046)
>     at Module.load (internal/modules/cjs/loader.js:701:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:625:3)
>     at Module.require (/app.asar/static/index.js:72:46)
>     at require (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:146814)
>     at /packages/atom-watchless/node_modules/graceful-fs/graceful-fs.js:3:27)
>     at /packages/atom-watchless/node_modules/graceful-fs/graceful-fs.js:160:3)
>     at Module.get_Module._compile (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:147498)
>     at Object.value [as .js] (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:151046)
>     at Module.load (internal/modules/cjs/loader.js:701:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:625:3)
>     at Module.require (/app.asar/static/index.js:72:46)
>     at require (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:146814)
>     at /packages/atom-watchless/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:3:10)
>     at /packages/atom-watchless/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:18:3)
>     at Module.get_Module._compile (C:/ProgramData/vscode/atom/app-1.50.0/resources/app/static/<embedded>:11:147498)
> ```
> 
> ### Befehle
> ### Nicht-Kernpakete
> ```
> a-package-loader 1.0.0 
> atom-folding 0.0.9 
> atom-material-syntax 1.0.8 
> atom-material-ui 2.1.3 
> atom-watch 0.1.0 
> atom-watcher 1.1.7 
> atom-watchless 0.7.0 
> auto-detect-indentation 1.3.0 
> auto-run 0.2.1 
> autocomplete-clang 0.13.1 
> autoreload-package-service 0.0.4 
> build 0.70.0 
> build-platformio 1.2.4 
> busy-signal 2.0.1 
> compile-watch 0.1.4 
> event-watch 4.1.11 
> f5-run-file 0.1.1 
> fetch-from-url 0.1.2 
> file-icons 2.1.47 
> file-open-watch 1.0.0 
> file-watcher 2.0.0 
> hey-pane 1.2.0 
> indent-detective 0.4.0 
> intentions 2.1.1 
> jsformat 0.9.3 
> language-ini 1.25.0 
> linter 3.4.0 
> linter-gcc2 0.8.8 
> linter-ui-default 3.4.1 
> platformio-aia 0.0.5 
> platformio-ide 2.7.2 
> platformio-ide-debugger 1.2.6 
> platformio-ide-terminal 2.10.1 
> platomformio 0.7.1 
> rdocumentation-browser 1.1.4 
> reload-button 0.1.0 
> reload-window 1.0.0 
> reload-workspace-button 0.1.2 
> remove-all-keybindings 0.2.1 
> run 0.0.1 
> run-in-atom 1.0.5 
> show-in-folder 0.6.0 
> teletype 0.13.4 
> teletype-revit-linker 1.0.0 
> terminal-commands 1.5.0 
> tokamak-terminal 10.0.1 
> tool-bar 1.4.4 
> zentabs 0.8.9 
> ```
